# Generated by Django 5.2 on 2025-06-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('product_name', models.CharField(max_length=20)),
                ('product_category', models.CharField(max_length=10)),
                ('product_description', models.TextField(max_length=20)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='Media/Products/')),
            ],
        ),
    ]
