# Generated by Django 5.2 on 2025-06-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to='Products/'),
        ),
    ]
