# Generated by Django 5.2 on 2025-06-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_alter_products_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(),
        ),
    ]
